name: OIDC TESTING

on:
  push:
    branches:
      - main

jobs:
   aws-connection:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - name: OIDC Connection
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a 
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::673725944222:role/github-actions-role
    - name: Successfully Login
      run:
        echo "HOla"
        
     
