name: OIDC TESTING

on:
  push:
    branches:
      - main

jobs:
   aws-connection:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
    - name: OIDC Connection
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::673725944222:role/github-actions-role
    - name: Successfully Login
      run:
        echo "Hola"
